version: '3'

services:
  db:
    image: postgres:13
    container_name: argentus-memory
    env_file:
      - .env
    ports:
      - "5432:5432"
  web:
    build:
      context: .
    container_name: argentus-box
    depends_on:
      - db
    command: ["./deploy.sh"]
